id: P004397
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG13770
  title: དེང་རབས་ཀྱི་བཟའ་བཏུང་གི་འཕྲོད་བསྟེན་བྱ་ཚུལ་མདོར་བསྡུས།
  author: ''
  volumes:
    fbc5dff3d0774da9b62c1aea0bfb037b:
      image_group_id: I1KG15221
      title: ''
      volume_number: 1
      total_pages: 48
      base_file: v001.txt
