id: I4B645320
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T15:48:37+00:00'
last_modified: '2022-06-07T22:34:48.605022+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13770
  title: དེང་རབས་ཀྱི་བཟའ་བཏུང་གི་འཕྲོད་བསྟེན་བྱ་ཚུལ་མདོར་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A15C:
      image_group_id: I1KG15221
      title: ''
      total_pages: 48
      order: 1
      base_file: A15C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
